#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
常量定义模块

定义应用程序中使用的常量
"""

# 应用程序常量
APP_NAME = "本地密码管理器"
APP_VERSION = "1.0.0"
APP_AUTHOR = "开发团队"

# 文件扩展名
DATA_FILE_EXTENSION = ".enc"
BACKUP_FILE_EXTENSION = ".enc"
CONFIG_FILE_EXTENSION = ".json"
LOG_FILE_EXTENSION = ".log"

# 加密常量
AES_KEY_LENGTH = 32  # AES-256
AES_IV_LENGTH = 16   # AES块大小
SALT_LENGTH = 32     # 盐值长度
PBKDF2_ITERATIONS = 100000  # PBKDF2迭代次数

# 密码强度等级
PASSWORD_STRENGTH_VERY_WEAK = 0
PASSWORD_STRENGTH_WEAK = 1
PASSWORD_STRENGTH_MEDIUM = 2
PASSWORD_STRENGTH_STRONG = 3
PASSWORD_STRENGTH_VERY_STRONG = 4

# 密码强度分数阈值
PASSWORD_SCORE_VERY_WEAK = 20
PASSWORD_SCORE_WEAK = 40
PASSWORD_SCORE_MEDIUM = 60
PASSWORD_SCORE_STRONG = 80

# 字符集定义
LOWERCASE_CHARS = "abcdefghijklmnopqrstuvwxyz"
UPPERCASE_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
DIGIT_CHARS = "0123456789"
SYMBOL_CHARS = "!@#$%^&*()_+-=[]{}|;:,.<>?"

# 默认配置值
DEFAULT_PASSWORD_LENGTH = 12
DEFAULT_CLIPBOARD_TIMEOUT = 10  # 秒
DEFAULT_PASSWORD_EXPIRY_DAYS = 90  # 天
DEFAULT_AUTO_LOCK_TIMEOUT = 300  # 秒
DEFAULT_BACKUP_INTERVAL = 7  # 天

# 窗口配置
DEFAULT_WINDOW_WIDTH = 800
DEFAULT_WINDOW_HEIGHT = 600
MIN_WINDOW_WIDTH = 600
MIN_WINDOW_HEIGHT = 400
MAX_WINDOW_WIDTH = 1920
MAX_WINDOW_HEIGHT = 1080

# 限制值
MIN_PASSWORD_LENGTH = 4
MAX_PASSWORD_LENGTH = 128
MAX_PLATFORM_NAME_LENGTH = 50
MAX_USERNAME_LENGTH = 100
MAX_NOTES_LENGTH = 500
MAX_LOGIN_ATTEMPTS = 3
MAX_BACKUP_FILES = 10

# 时间常量
SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR = 3600
SECONDS_PER_DAY = 86400
MILLISECONDS_PER_SECOND = 1000

# 文件大小常量
KB = 1024
MB = KB * 1024
GB = MB * 1024

# 日志配置
LOG_MAX_FILE_SIZE = 10 * MB
LOG_BACKUP_COUNT = 5
TEMP_FILE_CLEANUP_HOURS = 24
BACKUP_CLEANUP_DAYS = 30

# UI常量
AVAILABLE_THEMES = ["default", "dark", "light"]
DEFAULT_THEME = "default"

# 颜色常量（十六进制）
COLOR_PRIMARY = "#2C3E50"      # 深蓝色
COLOR_SECONDARY = "#ECF0F1"    # 浅灰色
COLOR_SUCCESS = "#27AE60"      # 绿色
COLOR_WARNING = "#F39C12"      # 橙色
COLOR_DANGER = "#E74C3C"       # 红色
COLOR_INFO = "#3498DB"         # 蓝色
COLOR_LIGHT = "#F8F9FA"        # 浅色
COLOR_DARK = "#343A40"         # 深色

# 字体大小
FONT_SIZE_SMALL = 10
FONT_SIZE_NORMAL = 12
FONT_SIZE_LARGE = 14
FONT_SIZE_TITLE = 16

# 间距常量
PADDING_SMALL = 5
PADDING_MEDIUM = 10
PADDING_LARGE = 15
MARGIN_SMALL = 5
MARGIN_MEDIUM = 10
MARGIN_LARGE = 15

# 消息类型
MSG_TYPE_INFO = "info"